### ISSUE TITLE
Viewing a 'draft' application - missing information:

### ISSUE THREAD

**Issue by YorgunKelebek** [goofballLogic/g4a-spa#10]
Viewing a 'draft' application - missing information:

![image](https://user-images.githubusercontent.com/56796626/120116109-70f3d480-c17e-11eb-942d-5eab93d75a76.png)

In terms of 'progressing' a draft application, this would be useful for submitting/cancelling on behalf of the applicant.

_Originally posted by @YorgunKelebek in https://github.com/goofballLogic/g4a-spa/issues/7#issuecomment-851042724_

**Comment by goofballLogic** [comment]
Is there a way to recreate this? When I view a draft application, this is what I see:

![Screen Shot 2021-05-31 at 10 21 54](https://user-images.githubusercontent.com/910448/120171642-29ab2980-c1fa-11eb-8f42-042c6f132a25.png)

**Comment by YorgunKelebek** [comment]
I think this might be when the application form has been cloned from the grant but not yet filled in..?

**Comment by goofballLogic** [comment]
Not that I can see:

![Screen Shot 2021-05-31 at 20 43 07](https://user-images.githubusercontent.com/910448/120234956-ef20ab80-c250-11eb-854a-b2194e875e21.png)

**Comment by goofballLogic** [comment]
Are you actually able to recreate it now?

**Comment by goofballLogic** [comment]
Can you just check - is _this_ what you are seeing? (Note the 404 below)

![Screen Shot 2021-05-31 at 21 06 23](https://user-images.githubusercontent.com/910448/120238026-25135f00-c254-11eb-8c53-2fc8f6798519.png)

**Comment by YorgunKelebek** [comment]
> Can you just check - is _this_ what you are seeing? (Note the 404 below)
> 
> ![Screen Shot 2021-05-31 at 21 06 23](https://user-images.githubusercontent.com/910448/120238026-25135f00-c254-11eb-8c53-2fc8f6798519.png)

Yes!

**Comment by goofballLogic** [comment]
ok thank you - this is a result of trying to view an application which originates outside of your tenancy and the system rejecting it, which .... makes sense. I'll have a think about this.

**Comment by goofballLogic** [comment]
Ok I have made changes to the security model. Hopefully this bug is now fixed although we may see other odd behaviour now if I haven't caught all the edge cases.

**Comment by YorgunKelebek** [comment]
Tested OK
