### ISSUE TITLE
If I have a cancelled application - one that I have cancelled - should I not be able to start a new one, or at least 're-activate' the old one? Maybe a distinction between cancellations by the applicant (withdraw) vs grant admin..?

### ISSUE THREAD

**Issue by YorgunKelebek** [goofballLogic/g4a-spa#11]
> If I have a cancelled application - one that I have cancelled - should I not be able to start a new one, or at least 're-activate' the old one? Maybe a distinction between cancellations by the applicant (withdraw) vs grant admin..?
> 
> ![image](https://user-images.githubusercontent.com/56796626/120116316-861d3300-c17f-11eb-97fc-cf334e3ce751.png)

fixed so you can apply again if you have a cancelled application.

_Originally posted by @goofballLogic in https://github.com/goofballLogic/g4a-spa/issues/7#issuecomment-851050640_

**Comment by YorgunKelebek** [comment]
I can view the cancelled application but I still cannot start a new application for the same grant... I should be able to either start a new one or reinstate my cancelled application.

**Comment by goofballLogic** [comment]
I can't recreate this. It's possible that it's fixed along with the others but if not it would be good to jump on a call to see what's happening.

**Comment by YorgunKelebek** [comment]
This is now working. I can create a new application for a grant I have a cancelled application...
