### ISSUE TITLE
Viewing a 'draft' application - missing information:

### ISSUE THREAD

**Issue by YorgunKelebek** [goofballLogic/g4a-spa#13]
> Viewing a 'draft' application - missing information:
> 
> ![image](https://user-images.githubusercontent.com/56796626/120116109-70f3d480-c17e-11eb-942d-5eab93d75a76.png)
> 
> In terms of 'progressing' a draft application, this would be useful for submitting/cancelling on behalf of the applicant.

this actually means something has gone wrong on the server. If you look in the Network tab of your browser you should see a 500 somewhere

_Originally posted by @goofballLogic in https://github.com/goofballLogic/g4a-spa/issues/7#issuecomment-851049111_

**Comment by YorgunKelebek** [comment]
Do you mean during the submission of the application or on the admin section when fetching the application?

**Comment by goofballLogic** [comment]
the latter - I don't know how to recreate this

**Comment by YorgunKelebek** [comment]
Same as issue #10 - closing as duplicate
