### ISSUE TITLE
The submission isn't actually supposed to be writeable at that point in the workflow as you can see in the workflow definition screen

### ISSUE THREAD

**Issue by YorgunKelebek** [goofballLogic/g4a-spa#14]
> removed

yeah the only thing which can't be changed is the "reason for progression" which you have to add when you click the button.

The submission isn't actually supposed to be writeable at that point in the workflow as you can see in the workflow definition screen:

![Screen Shot 2021-05-30 at 20 58 50](https://user-images.githubusercontent.com/910448/120118327-e618d700-c189-11eb-8ea0-1ce927cda756.png)

So I think there are 2 fixes here.

1. Update the workflow engine to prevent updating items when they aren't in a "writeable" status.
2. Remove the link to the reviewing screen when the application is approved/denied

_Originally posted by @goofballLogic in https://github.com/goofballLogic/g4a-spa/issues/7#issuecomment-851053479_

**Comment by YorgunKelebek** [comment]
I prefer option 1 above as it is a safer route

**Comment by goofballLogic** [comment]
Ugly but functional until we do some proper styling

![Screen Shot 2021-05-31 at 13 07 48](https://user-images.githubusercontent.com/910448/120191064-59196080-c211-11eb-8e1b-1d899d2018e1.png)

**Comment by goofballLogic** [comment]
Ok the "reviewing" link is now hidden if the underlying item is not _writeable_

**Comment by YorgunKelebek** [comment]
OK, works well
