### ISSUE TITLE
Add a link on the home page to find a grant page. Optionally, a list of all open grants can be listed on the home page

### ISSUE THREAD

**Issue by goofballLogic** [goofballLogic/g4a-spa#3]
@YorgunKelebek does this still make sense considering #2 ?

**Comment by YorgunKelebek** [comment]
> @YorgunKelebek does this still make sense considering #2 ?

I think the second part - list of open grants perhaps? But otherwise no...

**Comment by goofballLogic** [comment]
Given #2 we wouldn't expect non admin users to visit this page any more so I don't think we need this

**Comment by YorgunKelebek** [comment]
Agreed
