### ISSUE TITLE
Disallow starting multiple applications for the same grant by showing a warning message and the status of their existing application

### ISSUE THREAD

**Issue by goofballLogic** [goofballLogic/g4a-spa#5]

**Comment by goofballLogic** [comment]
![Screen Shot 2021-05-20 at 19 12 12](https://user-images.githubusercontent.com/910448/119028430-5b70f480-b99f-11eb-9aa2-de4d9611caf5.png)

**Comment by YorgunKelebek** [comment]
There is a rouge comma between the list items
![image](https://user-images.githubusercontent.com/56796626/119253277-5fbc2e00-bba8-11eb-9d10-404f7423e233.png)

**Comment by goofballLogic** [comment]
i think this must be for an old version @YorgunKelebek - that screen shouldn't even show up in the main portal any more.

**Comment by YorgunKelebek** [comment]
Yes, just seen the new portal :-)
