### ISSUE TITLE
On the portal, as an applicant, I would like to be able to 'preview' my submitted applications? And see their progress?

### ISSUE THREAD

**Issue by YorgunKelebek** [goofballLogic/g4a-spa#6]

**Comment by goofballLogic** [comment]
What does it mean to "Preview" an application? Is this seeing a read-only view before submission? In which case... Wouldn't I want to have that functionality after submitting as well?

**Comment by goofballLogic** [comment]
Still need your answers to the above @YorgunKelebek but meanwhile there's a starter for 10:

"View your application" link:
![Screen Shot 2021-05-23 at 20 15 35](https://user-images.githubusercontent.com/910448/119273657-c91d5a80-bc03-11eb-86a3-2e72aaca6f08.png)

Links to read-only view:
![Screen Shot 2021-05-23 at 20 15 44](https://user-images.githubusercontent.com/910448/119273659-cb7fb480-bc03-11eb-9815-aa69ca3f1f67.png)

**Comment by YorgunKelebek** [comment]
> What does it mean to "Preview" an application? Is this seeing a read-only view before submission? In which case... Wouldn't I want to have that functionality after submitting as well?

I mean seeing a read-only copy after submission i.e can't edit/re-submit. What you have done is fine.

**Comment by YorgunKelebek** [comment]
Will leave the issue open until 'status' of the application is available, which I assume will be done through #7
