### ISSUE TITLE
Ability to assess applications, add notes and comments, follow a process workflow, and record a final decision status: awarded/rejected with reason

### ISSUE THREAD

**Issue by YorgunKelebek** [goofballLogic/g4a-spa#7]

**Comment by goofballLogic** [comment]
Ah ok so I can see "Submitted" at the moment we don't have any other statuses for applications. Should we add some? Or do we need the concept of a workflow which grant admins can apply to a grant?

**Comment by YorgunKelebek** [comment]
> Ah ok so I can see "Submitted" at the moment we don't have any other statuses for applications. Should we add some? Or do we need the concept of a workflow which grant admins can apply to a grant?

Yes, I think admins should take the application through each step/status...

**Comment by YorgunKelebek** [comment]
I cannot see any of the applications for my grants:

![image](https://user-images.githubusercontent.com/56796626/120114563-97fad800-c177-11eb-8999-c23082ea7c9e.png)

Although I know there are some:

![image](https://user-images.githubusercontent.com/56796626/120114586-ad700200-c177-11eb-9f66-f890a07e7139.png)

**Comment by YorgunKelebek** [comment]
Viewing a 'draft' application - missing information:

![image](https://user-images.githubusercontent.com/56796626/120116109-70f3d480-c17e-11eb-942d-5eab93d75a76.png)

In terms of 'progressing' a draft application, this would be useful for submitting/cancelling on behalf of the applicant.

**Comment by YorgunKelebek** [comment]
Minor point, but I think the submit/cancel button colours should be reversed. Cancel is more of a 'red' action

![image](https://user-images.githubusercontent.com/56796626/120116231-17d87080-c17f-11eb-8974-04beaeb367dc.png)

**Comment by YorgunKelebek** [comment]
If I have a cancelled application - one that I have cancelled - should I not be able to start a new one, or at least 're-activate' the old one? Maybe a distinction between cancellations by the applicant (withdraw) vs grant admin..?

![image](https://user-images.githubusercontent.com/56796626/120116316-861d3300-c17f-11eb-97fc-cf334e3ce751.png)

**Comment by YorgunKelebek** [comment]
Unnecessary display of 'progress application' with reason for a complete application (rejected/approved)

![image](https://user-images.githubusercontent.com/56796626/120116384-d09eaf80-c17f-11eb-926e-2bfa8612138b.png)

**Comment by YorgunKelebek** [comment]
A navigation link back to list of applications from the application view screen would be useful.

**Comment by YorgunKelebek** [comment]
Amending review notes for a complete application (rejected/approved) should not be possible..? At the moment it is possible to change the notes, which might mean any evidence on the decision may be removed/changed.

**Comment by goofballLogic** [comment]
> Viewing a 'draft' application - missing information:
> 
> ![image](https://user-images.githubusercontent.com/56796626/120116109-70f3d480-c17e-11eb-942d-5eab93d75a76.png)
> 
> In terms of 'progressing' a draft application, this would be useful for submitting/cancelling on behalf of the applicant.

this actually means something has gone wrong on the server. If you look in the Network tab of your browser you should see a 500 somewhere

**Comment by goofballLogic** [comment]
> Unnecessary display of 'progress application' with reason for a complete application (rejected/approved)
> 
> ![image](https://user-images.githubusercontent.com/56796626/120116384-d09eaf80-c17f-11eb-926e-2bfa8612138b.png)

fixed

**Comment by goofballLogic** [comment]
> If I have a cancelled application - one that I have cancelled - should I not be able to start a new one, or at least 're-activate' the old one? Maybe a distinction between cancellations by the applicant (withdraw) vs grant admin..?
> 
> ![image](https://user-images.githubusercontent.com/56796626/120116316-861d3300-c17f-11eb-97fc-cf334e3ce751.png)

fixed so you can apply again if you have a cancelled application.

**Comment by goofballLogic** [comment]
> Minor point, but I think the submit/cancel button colours should be reversed. Cancel is more of a 'red' action
> 
> ![image](https://user-images.githubusercontent.com/56796626/120116231-17d87080-c17f-11eb-8974-04beaeb367dc.png)

The intent here was to indicate that if you "Submit" there's no going back. The consequences of submitting an application which isn't ready are probably more catastrophic for an applicant than accidentally cancelling. However - I think we're a bit limited by Bootstrap's colour scheme here. The possibilities out-of-the-box are shown in this screenshot:

![Screen Shot 2021-05-30 at 20 43 06](https://user-images.githubusercontent.com/910448/120117940-b963c000-c187-11eb-9e64-e325806e9e78.png)

I'd like to redesign to not use a crappy framework when we get the chance to redesign. Until then do you have alternative colour suggestions?

**Comment by goofballLogic** [comment]
> I cannot see any of the applications for my grants:
> 
> ![image](https://user-images.githubusercontent.com/56796626/120114563-97fad800-c177-11eb-8999-c23082ea7c9e.png)
> 
> Although I know there are some:
> 
> ![image](https://user-images.githubusercontent.com/56796626/120114586-ad700200-c177-11eb-9f66-f890a07e7139.png)

Can you check whether this was a caching issue?

**Comment by goofballLogic** [comment]
> A navigation link back to list of applications from the application view screen would be useful.

fixed

**Comment by goofballLogic** [comment]
> removed

yeah the only thing which can't be changed is the "reason for progression" which you have to add when you click the button.

The submission isn't actually supposed to be writeable at that point in the workflow as you can see in the workflow definition screen:

![Screen Shot 2021-05-30 at 20 58 50](https://user-images.githubusercontent.com/910448/120118327-e618d700-c189-11eb-8ea0-1ce927cda756.png)

So I think there are 2 fixes here.

1. Update the workflow engine to prevent updating items when they aren't in a "writeable" status.
2. Remove the link to the reviewing screen when the application is approved/denied

**Comment by YorgunKelebek** [comment]
> The intent here was to indicate that if you "Submit" there's no going back. The consequences of submitting an application which isn't ready are probably more catastrophic for an applicant than accidentally cancelling. However - I think we're a bit limited by Bootstrap's colour scheme here. The possibilities out-of-the-box are shown in this screenshot:

I understand your thinking, but still believe that submitting an application is a 'positive' action, where as cancelling it is a 'negative' one...

How about orange for submit and red for cancel?

**Comment by goofballLogic** [comment]
> > The intent here was to indicate that if you "Submit" there's no going back. The consequences of submitting an application which isn't ready are probably more catastrophic for an applicant than accidentally cancelling. However - I think we're a bit limited by Bootstrap's colour scheme here. The possibilities out-of-the-box are shown in this screenshot:
> 
> I understand your thinking, but still believe that submitting an application is a 'positive' action, where as cancelling it is a 'negative' one...
> 
> How about orange for submit and red for cancel?

I've changed it over to use the bootstrap "warn" colour for submit and moved the "danger" to the Cancel button

**Comment by YorgunKelebek** [comment]
The process works as intended. After approving a grant application, as a grant administrator, I could accept/decline the offer of grant on behalf of the applicant. Should these be available to the grant administrator?

**Comment by goofballLogic** [comment]
I think it makes sense (at least for now) that the grant administrator can push the button on behalf of a candidate if the candidate is only able to e.g. agree acceptance via a telephone call. Basically there should be some way for a grant manager to override the normal process of accept/decline on behalf of the applicant which should only be used in extreme circumstances.

At the moment the workflow is:

`grant` --> `application` --> `submitted application`

We could remove these buttons from the grant manager's screen by further breaking up the workflow like this:

`grant` --> `application` --> `submitted application` --> `approved application` --> `accepted funding`

**Comment by goofballLogic** [comment]
I'll break out this discussion to a distinct issue so that this monster can go to done
