### ISSUE TITLE
Applications are not segregated to the correct portal

### ISSUE THREAD

**Issue by goofballLogic** [goofballLogic/g4a-spa#9]
![Screenshot_2021-05-30-19-50-16-947_com android chrome](https://user-images.githubusercontent.com/910448/120116577-a39ecc80-c180-11eb-94a7-caa1fad963e5.jpg)

**Comment by YorgunKelebek** [comment]
Seems like a new bug has been introduced by this fix:

When starting a new application I cannot see the application form to work on, although attempting to start another picks it up correctly.

![image](https://user-images.githubusercontent.com/56796626/120122445-a8737880-c1a0-11eb-9fb6-3c17c973a114.png)

![image](https://user-images.githubusercontent.com/56796626/120122449-b0331d00-c1a0-11eb-968a-4f7c2e82a30a.png)

**Comment by YorgunKelebek** [comment]
Cover with issue #12 - closing this one
